### ISSUE TITLE
Move jest config to extends instead of overrides

### ISSUE THREAD

**Issue by tclindner** [tclindner/eslint-config-tc#221]
> > * Adds the other new "recommended" rules from v24 (why don't we just use their recommendations?)
> 
> 
> 
> Right now we do everything in overrides, which don't support extends. We can add the jest rules so they apply to all files. What do you think?

Yea that's fine. Just seems like unnecessary maintenance.

_Originally posted by @pohnemus in https://github.com/tclindner/eslint-config-tc/pull/219#issuecomment-687651100_

### Tasks

- [x] Add Jest recommended (`plugin:jest/recommended`) config to `extends` section. See https://www.npmjs.com/package/eslint-plugin-jest#recommended
- [x] Remove all `jest/*` rules from overrides - https://github.com/tclindner/eslint-config-tc/blob/master/index.js#L41
- [x] Move the following rules to a new `jest` file in the `rules` directory. `jest/no-alias-methods`, `jest/no-duplicate-hooks`, `jest/no-if`, `jest/no-large-snapshots`, `jest/no-test-return-statement`, `jest/prefer-called-with`, `jest/prefer-hooks-on-top`, `jest/prefer-strict-equal`, `jest/prefer-to-be-null`, `jest/prefer-to-be-undefined`, `jest/prefer-to-contain`, `jest/prefer-to-have-length`, `jest/prefer-todo`, `jest/require-to-throw-message`, and `jest/require-top-level-describe`.
